theme: jekyll-theme-minimal

title: Mtradumàtica
description: MTradumàtica is a free, Moses-based web platform for training and using statistical machine translation systems with a user-friendly graphical interface.
