theme: jekyll-theme-minimal

title: Mtradumàtica
description: Free Statistical Machine Translation Customisation for Translators.

image:(https://github.com/tradumatica/tradumatica.github.io/blob/master/Captura%20de%20pantalla%202018-05-09%20a%20les%2014.16.50.png)
