theme: jekyll-theme-minimal

title: Mtradumàtica
description: Free Statistical Machine Translation Customisation for Translators.
title-img: https://github.com/tradumatica/tradumatica.github.io/blob/master/docs/tradumatica-logo.png
